Repository JNU-econovation/girin-grim, pull requests merged in 2023-12, with the labels that each got.

#9 [BE] 회원가입 기능
  BE/girin-grim/build.gradle
  BE/girin-grim/src/main/java/com/example/giringrim/favUniversity/FavUniversity.java
  BE/girin-grim/src/main/java/com/example/giringrim/favUniversity/FavUniversityRepository.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/Member.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/MemberController.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/MemberRepository.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/MemberReqDto.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/MemberService.java
  BE/girin-grim/src/main/java/com/example/giringrim/utils/ApiResponse.java
  BE/girin-grim/src/main/java/com/example/giringrim/utils/ApiResponseGenerator.java
  BE/girin-grim/src/main/java/com/example/giringrim/utils/exception/Error.java
  BE/girin-grim/src/main/java/com/example/giringrim/utils/exception/ErrorMessage.java
  BE/girin-grim/src/main/java/com/example/giringrim/utils/exception/GlobalExceptionHandler.java
  BE/girin-grim/src/main/resources/application-dev.yml
  BE/girin-grim/src/main/resources/application.properties
  BE/girin-grim/src/main/resources/application.yml
Labels: BE, :sparkles: Feature

#11 [BE] 전국 대학교 리스트 검색 및 조회기능
  BE/girin-grim/src/main/java/com/example/giringrim/member/MemberServiceImpl.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/exception/EmailAlreadyExistException.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/exception/NicknameAlreadyExistException.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/exception/UniversitySelectionException.java
  BE/girin-grim/src/main/java/com/example/giringrim/university/UnivController.java
  BE/girin-grim/src/main/java/com/example/giringrim/university/UnivRepository.java
  BE/girin-grim/src/main/java/com/example/giringrim/university/UnivResponseDto.java
  BE/girin-grim/src/main/java/com/example/giringrim/university/UnivService.java
  BE/girin-grim/src/main/java/com/example/giringrim/university/University.java
  BE/girin-grim/src/main/java/com/example/giringrim/university/exception/RegionNotExistException.java
  BE/girin-grim/src/main/java/com/example/giringrim/university/exception/UnivNotExistException.java
  BE/girin-grim/src/main/java/com/example/giringrim/utils/exception/ErrorMessage.java
  BE/girin-grim/src/main/java/com/example/giringrim/utils/exception/GlobalExceptionHandler.java
Labels: BE, :sparkles: Feature

#14 [BE/FEAT] api 스펙에 따른 변경사항 수정, 프로필 조회 기능
  BE/girin-grim/src/main/java/com/example/giringrim/favUniversity/FavUniversityRepository.java
  BE/girin-grim/src/main/java/com/example/giringrim/favUniversity/entity/FavUniversity.java
  BE/girin-grim/src/main/java/com/example/giringrim/favUniversity/repository/FavUniversityRepository.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/MemberController.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/MemberService.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/MemberServiceImpl.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/controller/MemberController.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/dto/MemberReqDtos.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/dto/MemberRespDtos.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/entity/Member.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/repository/MemberRepository.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/service/MemberService.java
  BE/girin-grim/src/main/java/com/example/giringrim/member/service/MemberServiceImpl.java
  BE/girin-grim/src/main/java/com/example/giringrim/university/controller/UnivController.java
  BE/girin-grim/src/main/java/com/example/giringrim/university/dto/UnivRespDtos.java
  BE/girin-grim/src/main/java/com/example/giringrim/university/entity/University.java
  BE/girin-grim/src/main/java/com/example/giringrim/university/repository/UnivRepository.java
  BE/girin-grim/src/main/java/com/example/giringrim/university/service/UnivService.java
  BE/girin-grim/src/main/java/com/example/giringrim/utils/SecurityConfig.java
  BE/girin-grim/src/main/java/com/example/giringrim/utils/exception/GlobalExceptionHandler.java
Labels: BE

#22 feat: Logo 리다이렉트 추가
  FE/src/components/layout/HeaderLogoSection.tsx
Labels: FE, :sparkles: Feature
