Repository JNU-econovation/girin-grim, pull requests merged in 2024-01, with the labels that each got.

#29 [BE] 펀딩 상세정보 조회 기능
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/controller/FundingController.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/dto/FundingRespDtos.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/service/FundingService.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/service/FundingServiceImpl.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/option/item/ItemRepository.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/utils/exception/ErrorMessage.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/utils/exception/GlobalExceptionHandler.java
Labels: BE, :sparkles: Feature

#36 [BE/FEAT] 홈 메인페이지 조회 기능
  BE/girin-grim/.idea/compiler.xml
  BE/girin-grim/gradlew
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/controller/FundingController.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/dto/FundingRespDtos.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/entity/Funding.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/entity/FundingType.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/repository/FundingRepositoryCustom.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/repository/FundingSearchCondition.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/repository/QuerydslConfiguration.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/service/FundingService.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/service/FundingServiceImpl.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/member/entity/Member.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/member/service/MemberService.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/member/service/MemberServiceImpl.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/utils/security/SecurityConfig.java
Labels: BE, :sparkles: Feature

#41 fix: 펀딩 상세페이지 옵션 공유버그 수정
  FE/src/app/api/funding/[fundinId]/route.ts
  FE/src/app/api/home/route.ts
  FE/src/components/fundingDetail/InfoOption.tsx
Labels: bug, FE

#43 chore: image태그 remote설정
  FE/next.config.js
  FE/public/assets/Image.jpg
  FE/src/app/api/funding/[fundinId]/route.ts
  FE/src/components/fundingDetail/FundingDetail.tsx
  FE/src/components/fundingDetail/InfoOption.tsx
Labels: FE

#45 Feat/#44
  FE/next.config.js
  FE/public/assets/Image.jpg
  FE/src/apis/apis.ts
  FE/src/app/api/funding/[fundinId]/description/route.ts
  FE/src/app/funding/[fundingId]/page.tsx
  FE/src/components/fundingDetail/Detail/Description.tsx
  FE/src/components/fundingDetail/Detail/DetailDescription.tsx
  FE/src/components/fundingDetail/Detail/NavBar.tsx
  FE/src/components/fundingDetail/Info/DeleteBtn.tsx
  FE/src/components/fundingDetail/Info/FundingDetail.tsx
  FE/src/components/fundingDetail/Info/FundingDetailBtnSection.tsx
  FE/src/components/fundingDetail/Info/FundingInfo.tsx
  FE/src/components/fundingDetail/Info/FundingInfoCost.tsx
  FE/src/components/fundingDetail/Info/FundingInfoTag.tsx
  FE/src/components/fundingDetail/Info/InfoDate.tsx
  FE/src/components/fundingDetail/Info/InfoHeader.tsx
  FE/src/components/fundingDetail/Info/InfoOption.tsx
  FE/src/components/fundingDetail/Info/InfoOptionDetail.tsx
  FE/src/constants/FundingDetailDate.ts
  FE/src/hooks/useFundingDescription.tsx
Labels: FE, :sparkles: Feature

#47 fix: 옵션 삭제시 클릭된 옵션 설정 초기화
  FE/src/components/fundingDetail/Info/InfoOption.tsx
Labels: bug, FE

#49 Feat/#48
  FE/src/apis/apis.ts
  FE/src/app/api/member/route.ts
  FE/src/components/layout/Header.tsx
  FE/src/components/layout/HeaderLogoSection.tsx
  FE/src/components/layout/UserImage.tsx
  FE/src/hooks/useUser.tsx
Labels: FE, :sparkles: Feature

#52 [BE] 결제하기, 후원 상세 내역 조회
  BE/girin-grim/src/main/java/com/starshop/giringrim/favUniversity/entity/FavUniversity.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/dto/FundingRespDtos.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/entity/Funding.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/member/entity/Member.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/option/item/Item.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/Payment.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/PaymentController.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/PaymentRepository.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/PaymentReqDtos.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/PaymentRespDtos.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/PaymentService.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/details/PaymentDetails.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/details/PaymentDetailsRepository.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/exception/CoinNotEnoughException.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/exception/PaymentAlreadyDoneException.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/exception/PaymentOptionNotExistException.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/exception/QuantityNotEnoughException.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/university/entity/University.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/utils/exception/ErrorMessage.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/utils/exception/GlobalExceptionHandler.java
Labels: BE, :sparkles: Feature

#54 Feat/#50
  FE/public/assets/Rectangle.svg
  FE/src/Model/Funding.ts
  FE/src/Model/Local.ts
  FE/src/Model/Response.ts
  FE/src/apis/apis.ts
  FE/src/app/api/charge/route.ts
  FE/src/app/api/funding/[fundinId]/payment/route.ts
  FE/src/app/api/funding/payment/route.ts
  FE/src/app/funding/pledge/[fundingId]/page.tsx
  FE/src/components/common/icon.ts
  FE/src/components/common/icons/Address.tsx
  FE/src/components/common/icons/Phone.tsx
  FE/src/components/common/icons/Rectangle.tsx
  FE/src/components/common/icons/Ticket.tsx
  FE/src/components/fundingDetail/Info/FundingDetail.tsx
  FE/src/components/fundingDetail/Info/FundingDetailBtnSection.tsx
  FE/src/components/fundingDetail/Info/FundingInfo.tsx
  FE/src/components/fundingDetail/Info/FundingInfoCost.tsx
  FE/src/components/fundingDetail/Info/FundingInfoTag.tsx
  FE/src/components/fundingDetail/Info/InfoDate.tsx
  FE/src/components/fundingDetail/Info/InfoHeader.tsx
  FE/src/components/fundingDetail/Info/InfoOption.tsx
  FE/src/components/layout/HeaderLogoSection.tsx
  FE/src/components/layout/UserImage.tsx
  FE/src/components/pledge/Agreement.tsx
  FE/src/components/pledge/CostInfo.tsx
  FE/src/components/pledge/InfoSection.tsx
  FE/src/components/pledge/OptinsSection.tsx
  FE/src/components/pledge/Options.tsx
  FE/src/components/pledge/Payment.tsx
  FE/src/components/pledge/PaymentBg.tsx
  FE/src/components/pledge/PaymentBtn.tsx
  FE/src/components/pledge/Pledge.tsx
  FE/src/components/pledge/SuppotInfo.tsx
  FE/src/constants/Pledge.tsx
  FE/src/hooks/useCharge.tsx
  FE/src/hooks/usePledge.tsx
  FE/src/hooks/useUser.tsx
  FE/src/store/FundingState.ts
  FE/src/utils/dataFomet.ts
  FE/src/utils/date.ts
  FE/src/utils/localData.ts
  FE/src/utils/payment.ts
Labels: FE, :sparkles: Feature

#61 Feat/#59
  FE/public/assets/FeedImage.svg
  FE/src/Model/Feed.ts
  FE/src/apis/apis.ts
  FE/src/app/api/home/route.ts
  FE/src/app/api/member/[memberId]/backed/route.ts
  FE/src/app/member/[memberId]/page.tsx
  FE/src/app/page.tsx
  FE/src/components/common/Feed.tsx
  FE/src/components/common/Grid.tsx
  FE/src/components/common/NavBar.tsx
  FE/src/components/common/StyledBtn.tsx
  FE/src/components/fundingDetail/Detail/DetailDescription.tsx
  FE/src/components/fundingDetail/Detail/DetailNavBar.tsx
  FE/src/components/fundingDetail/Detail/NavBar.tsx
  FE/src/components/home/ExtendBtn.tsx
  FE/src/components/home/Grid.tsx
  FE/src/components/home/HomeFundingList.tsx
  FE/src/components/home/HomeHeader.tsx
  FE/src/components/home/Univ.tsx
  FE/src/components/join/SubmitBtn.tsx
  FE/src/components/member/FundingList/MemberFundingGridSection.tsx
  FE/src/components/member/FundingList/MemberFundingNav.tsx
  FE/src/components/member/memberInfo/CargeBtn.tsx
  FE/src/constants/memberData.tsx
  FE/src/hooks/useFeeds.tsx
  FE/src/hooks/useUserFeed.tsx
  FE/src/store/JoinState.ts
  FE/src/utils/Home.ts
Labels: FE, :sparkles: Feature

#62 fix: 리프레시시 총 금액 사라지는 버그 수정
  FE/src/components/common/icons/Coin.tsx
  FE/src/components/pledge/Payment.tsx
  FE/src/utils/localData.ts
  FE/src/utils/payment.ts
Labels: FE

#64 여러 수정사항들, 버그 수정
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/dto/FundingReqDtos.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/dto/FundingRespDtos.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/entity/Funding.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/service/FundingServiceImpl.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/member/controller/MemberController.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/member/dto/MemberRespDtos.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/member/entity/Member.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/member/exception/ParameterCountException.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/member/service/MemberServiceImpl.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/option/Option.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/option/item/ItemRepository.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/PaymentController.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/PaymentRepository.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/PaymentReqDtos.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/PaymentRespDtos.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/PaymentService.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/exception/HistoryForbiddenException.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/exception/HistoryNotExistException.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/utils/common/ApiResponse.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/utils/exception/ErrorMessage.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/utils/exception/GlobalExceptionHandler.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/utils/security/JwtAuthenticationFilter.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/utils/security/JwtExceptionFilter.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/utils/security/SecurityConfig.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/utils/security/exception/ForbiddenException.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/utils/security/exception/UnAuthorizedException.java
Labels: enhancement, BE

#65 Feat/#63
  FE/src/Model/Backed.ts
  FE/src/apis/apis.ts
  FE/src/app/api/member/[memberId]/backed/[fundingId]/route.ts
  FE/src/app/member/[memberId]/backed/[fundingId]/page.tsx
  FE/src/app/member/[memberId]/page.tsx
  FE/src/components/backed/BackBtn.tsx
  FE/src/components/backed/BackedSection.tsx
  FE/src/components/backed/FundingInfo.tsx
  FE/src/components/common/Feed.tsx
  FE/src/components/common/FeedBox.tsx
  FE/src/components/common/Grid.tsx
  FE/src/components/common/HomeFeed.tsx
  FE/src/components/common/InfoSection.tsx
  FE/src/components/common/Notice.tsx
  FE/src/components/common/OptionContent.tsx
  FE/src/components/common/Options.tsx
  FE/src/components/common/PageTitle.tsx
  FE/src/components/common/Total.tsx
  FE/src/components/home/HomeFundingList.tsx
  FE/src/components/member/FundingList/MemberFundingGridSection.tsx
  FE/src/components/member/MemberHeader.tsx
  FE/src/components/pledge/OptinsSection.tsx
  FE/src/components/pledge/Payment.tsx
  FE/src/components/pledge/Pledge.tsx
  FE/src/constants/commonData.tsx
  FE/src/hooks/useBacked.tsx
  FE/src/utils/dataFomat.ts
  FE/src/utils/localData.ts
Labels: FE, :sparkles: Feature

#67 Feat/#66
  FE/public/assets/BankTransfer.svg
  FE/public/assets/Credit.svg
  FE/public/assets/DevBtn.svg
  FE/public/assets/Kakao.svg
  FE/src/Model/Coin.ts
  FE/src/apis/apis.ts
  FE/src/app/api/charge/route.ts
  FE/src/app/charge/page.tsx
  FE/src/components/charge/BalanceDisplay.tsx
  FE/src/components/charge/ChargeAgreement.tsx
  FE/src/components/charge/ChargeBtn.tsx
  FE/src/components/charge/ChargeInfo.tsx
  FE/src/components/charge/ChargeNav.tsx
  FE/src/components/charge/ChargeNoticet.tsx
  FE/src/components/charge/ChargeOption.tsx
  FE/src/components/charge/ChargeOptionSection.tsx
  FE/src/components/charge/ChargingCoin.tsx
  FE/src/components/charge/DevBtn.tsx
  FE/src/components/charge/PageDescription.tsx
  FE/src/components/charge/Payment.tsx
  FE/src/components/charge/PaymentAmountDisplay.tsx
  FE/src/components/common/InfoSection.tsx
  FE/src/components/common/Receipt.tsx
  FE/src/components/common/StyledBtn.tsx
  FE/src/components/common/Total.tsx
  FE/src/components/common/icon.ts
  FE/src/components/common/icons/BankTransfer.tsx
  FE/src/components/common/icons/Credit.tsx
  FE/src/components/common/icons/DevBtn.tsx
  FE/src/components/common/icons/Kakao.tsx
  FE/src/components/pledge/Payment.tsx
  FE/src/components/pledge/Pledge.tsx
  FE/src/constants/CategoryData.tsx
  FE/src/constants/ChargeDate.tsx
  FE/src/store/ChargeState.ts
Labels: FE, :sparkles: Feature

#68 [BE] 멤버 도메인 테스트 코드 작성
  BE/girin-grim/src/main/java/com/starshop/giringrim/member/service/MemberServiceImpl.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/payment/details/PaymentDetails.java
  BE/girin-grim/src/main/resources/application-test.yml
  BE/girin-grim/src/test/java/com/starshop/giringrim/DatabaseCleanup.java
  BE/girin-grim/src/test/java/com/starshop/giringrim/TestConfig.java
  BE/girin-grim/src/test/java/com/starshop/giringrim/member/controller/MemberControllerTest.java
Labels: BE, Test

#70 refactor: apis 문서 정리
  FE/src/apis/apis.ts
  FE/src/apis/charge.ts
  FE/src/apis/funding.ts
  FE/src/apis/home.ts
  FE/src/apis/uni.ts
  FE/src/app/api/funding/[fundingId]/description/route.ts
  FE/src/app/api/funding/[fundingId]/payment/route.ts
  FE/src/app/api/funding/[fundingId]/route.ts
  FE/src/app/api/funding/payment/route.ts
  FE/src/components/charge/ChargeBtn.tsx
  FE/src/components/fundingDetail/Info/FundingDetailBtnSection.tsx
  FE/src/components/fundingDetail/Info/InfoHeader.tsx
  FE/src/components/fundingDetail/Info/InfoOptionDetail.tsx
  FE/src/components/login/LoginForm.tsx
  FE/src/components/pledge/CostInfo.tsx
  FE/src/components/pledge/Payment.tsx
  FE/src/components/pledge/PaymentBtn.tsx
  FE/src/components/pledge/Pledge.tsx
  FE/src/constants/urls.ts
  FE/src/hooks/useCharge.tsx
  FE/src/hooks/useDuplicate.tsx
  FE/src/hooks/useFeeds.tsx
  FE/src/hooks/useFundingDescription.tsx
  FE/src/hooks/useFundingDetail.tsx
  FE/src/hooks/usePledge.tsx
  FE/src/hooks/useUniv.tsx
  FE/src/hooks/useUser.tsx
  FE/src/hooks/useUserDetail.tsx
Labels: FE, refactor

#75 feat: 필터 컴포넌트 추가
  FE/src/components/pages/home/HomeFilter.tsx
  FE/src/components/pages/home/HomeHeader.tsx
  FE/src/constants/HomeData.tsx
Labels: FE, :sparkles: Feature

#76 fix : 분기문 수정
  BE/girin-grim/src/main/java/com/starshop/giringrim/member/service/MemberServiceImpl.java
Labels: bug, BE

#80 feat: 서버 연결
  FE/next.config.js
  FE/src/Model/user.ts
  FE/src/apis/apis.ts
  FE/src/apis/axios/index.ts
  FE/src/apis/home.ts
  FE/src/components/pages/home/Univ.tsx
  FE/src/components/pages/join/DuplicateCheckButton.tsx
  FE/src/components/pages/login/LoginForm.tsx
  FE/src/components/pages/login/LoginInput.tsx
  FE/src/utils/Home.ts
  FE/src/utils/authenticate.ts
Labels: FE

#85 Feat/#82
  FE/src/Model/Backed.ts
  FE/src/Model/Funding.ts
  FE/src/Model/user.ts
  FE/src/apis/charge.ts
  FE/src/apis/funding.ts
  FE/src/apis/home.ts
  FE/src/apis/member.ts
  FE/src/app/funding/[fundingId]/page.tsx
  FE/src/components/common/Grid.tsx
  FE/src/components/common/InfoSection.tsx
  FE/src/components/common/icons/User.tsx
  FE/src/components/pages/backed/FundingInfo.tsx
  FE/src/components/pages/charge/BalanceDisplay.tsx
  FE/src/components/pages/fundingDetail/Detail/Description.tsx
  FE/src/components/pages/fundingDetail/Detail/DetailDescription.tsx
  FE/src/components/pages/fundingDetail/Info/FundingDetail.tsx
  FE/src/components/pages/join/DuplicateCheckButton.tsx
  FE/src/components/pages/join/JoinForm.tsx
  FE/src/components/pages/layout/HeaderNavSection.tsx
  FE/src/components/pages/layout/UserImage.tsx
  FE/src/components/pages/login/LoginForm.tsx
  FE/src/components/pages/member/memberInfo/InfoSectoin.tsx
  FE/src/components/pages/pledge/CostInfo.tsx
  FE/src/components/pages/pledge/Payment.tsx
  FE/src/components/pages/pledge/PaymentBtn.tsx
  FE/src/components/pages/pledge/Pledge.tsx
  FE/src/constants/responseData.tsx
  FE/src/hooks/useBacked.tsx
  FE/src/hooks/useUser.tsx
  FE/src/hooks/useUserDetail.tsx
  FE/src/hooks/useUserFeed.tsx
  FE/src/store/HomeState.ts
  FE/src/store/JoinState.ts
  FE/src/utils/authenticate.ts
  FE/src/utils/dataFomat.ts
Labels: FE

#87 Feat/#86
  FE/public/assets/Bubble.svg
  FE/public/assets/Girin.svg
  FE/public/assets/Girin1.svg
  FE/public/assets/Girin2.svg
  FE/public/assets/Girin3.svg
  FE/src/components/common/icon.ts
  FE/src/components/common/icons/Bubble.tsx
  FE/src/components/pages/fundingDetail/Info/FundingDetail.tsx
  FE/src/components/pages/fundingDetail/Info/GaugeBar.tsx
  FE/src/components/pages/fundingDetail/Info/GaugeBg.tsx
  FE/src/components/pages/fundingDetail/Info/Girin.tsx
Labels: FE, :sparkles: Feature

#89 Feat/#88
  FE/src/app/api/funding/[fundingId]/payment/route.ts
  FE/src/components/pages/pledge/AddressComponents.tsx
  FE/src/components/pages/pledge/PaymentBtn.tsx
  FE/src/components/pages/pledge/Pledge.tsx
  FE/src/components/pages/pledge/SuppotInfo.tsx
  FE/src/store/PledgeState.ts
  FE/src/utils/dataFomat.ts
Labels: FE, :sparkles: Feature

#91 Feat/#90
  FE/package.json
  FE/public/assets/ColoredFile.svg
  FE/public/assets/File.svg
  FE/src/Model/user.ts
  FE/src/components/common/AgreementCheckbox.tsx
  FE/src/components/common/HeaderHero.tsx
  FE/src/components/common/UnivTitle.tsx
  FE/src/components/common/icon.ts
  FE/src/components/common/icons/File.tsx
  FE/src/components/pages/join/DuplicateCheckButton.tsx
  FE/src/components/pages/join/JoinBtnInput.tsx
  FE/src/components/pages/join/JoinForm.tsx
  FE/src/components/pages/join/JoinInput.tsx
  FE/src/components/pages/join/UploadImage.tsx
  FE/src/components/pages/join/modal/Creator.tsx
  FE/src/components/pages/join/modal/Modal.tsx
  FE/src/components/pages/join/modal/Select.tsx
  FE/src/components/pages/join/modal/TypeModal.tsx
  FE/src/components/pages/join/modal/UnivUl.tsx
  FE/src/components/pages/join/modal/Upload.tsx
  FE/src/constants/formComponent.tsx
  FE/src/middleware.ts
  FE/src/service/aws.ts
  FE/src/store/HomeState.ts
  FE/src/store/JoinState.ts
  FE/src/utils/authenticate.ts
  FE/src/utils/cookieUtil.ts
  FE/src/utils/localData.ts
  FE/tsconfig.json
  FE/yarn.lock
Labels: FE, :sparkles: Feature

#93 Fix/#92
  FE/src/components/common/StyledBtn.tsx
  FE/src/components/pages/fundingDetail/Info/FundingDetail.tsx
  FE/src/components/pages/fundingDetail/Info/FundingDetailBtnSection.tsx
  FE/src/components/pages/fundingDetail/Info/FundingInfo.tsx
  FE/src/components/pages/fundingDetail/Info/FundingInfoCost.tsx
  FE/src/components/pages/fundingDetail/Info/GaugeBar.tsx
  FE/src/components/pages/fundingDetail/Info/GaugeBg.tsx
  FE/src/components/pages/fundingDetail/Info/Girin.tsx
  FE/src/components/pages/fundingDetail/Info/InfoDonate.tsx
  FE/src/components/pages/fundingDetail/Info/InfoOption.tsx
  FE/src/components/pages/join/JoinForm.tsx
  FE/src/components/pages/join/modal/Upload.tsx
  FE/src/utils/date.ts
  FE/tailwind.config.ts
Labels: bug, FE

#96 design: 전제척인 그리드 수정
  FE/public/assets/NameTagBt.svg
  FE/public/assets/NameTagTop.svg
Labels: FE

#99 Feat/#94
  FE/public/assets/Group 237943.png
  FE/public/assets/Layer.svg
  FE/public/assets/NameTag.png
  FE/public/assets/NameTagBt.png
  FE/src/apis/funding.ts
  FE/src/apis/home.ts
  FE/src/app/api/member/[memberId]/route.ts
  FE/src/components/common/InfoSection.tsx
  FE/src/components/common/StyledBtn.tsx
  FE/src/components/common/icons/Layer.tsx
  FE/src/components/common/icons/NameTag.tsx
  FE/src/components/common/icons/Rectangle.tsx
  FE/src/components/pages/charge/DevBtn.tsx
  FE/src/components/pages/fundingDetail/Info/FundingDetail.tsx
  FE/src/components/pages/fundingDetail/Info/GaugeBar.tsx
  FE/src/components/pages/fundingDetail/Info/Girin.tsx
  FE/src/components/pages/fundingDetail/Info/InfoDate.tsx
  FE/src/components/pages/fundingDetail/Info/InfoOption.tsx
  FE/src/components/pages/fundingDetail/Info/InfoOptionDetail.tsx
  FE/src/components/pages/home/Univ.tsx
  FE/src/components/pages/join/JoinForm.tsx
  FE/src/components/pages/layout/HeaderForm.tsx
  FE/src/components/pages/layout/HeaderNavSection.tsx
  FE/src/components/pages/layout/modal/UnivUlUniv.tsx
  FE/src/components/pages/member/memberInfo/InfoSectoin.tsx
  FE/src/components/pages/member/memberInfo/SettingBtn.tsx
  FE/src/components/pages/pledge/AddressComponents.tsx
  FE/src/components/pages/pledge/Agreement.tsx
  FE/src/components/pages/pledge/Payment.tsx
  FE/src/components/pages/pledge/PaymentBg.tsx
  FE/src/components/pages/pledge/PaymentBtn.tsx
  FE/src/store/HomeState.ts
  FE/src/utils/Home.ts
Labels: FE, :sparkles: Feature

#101 fix: 로그인시 헤더의 유저 아이콘 변경되지 않던 버그 수정
  FE/src/apis/member.ts
  FE/src/components/common/HeaderHero.tsx
  FE/src/components/pages/layout/Header.tsx
  FE/src/components/pages/layout/HeaderLogoSection.tsx
  FE/src/components/pages/layout/UserImage.tsx
  FE/src/components/pages/layout/modal/UserModal.tsx
  FE/src/components/pages/login/LoginForm.tsx
  FE/src/utils/authenticate.ts
  FE/src/utils/cookieUtil.ts
  FE/src/utils/cssFormat.ts
Labels: FE, :sparkles: Feature

#108 Design/#105
  FE/public/assets/All.svg
  FE/public/assets/AllSelected.svg
  FE/public/assets/DonateSelected.svg
  FE/public/assets/GiftSelected.svg
  FE/src/Model/user.ts
  FE/src/components/common/icons/All.tsx
  FE/src/components/common/icons/Donate.tsx
  FE/src/components/common/icons/Gift.tsx
  FE/src/components/common/icons/NameTag.tsx
  FE/src/components/pages/member/memberInfo/InfoSectoin.tsx
  FE/src/components/pages/member/memberInfo/MemberInfoList.tsx
  FE/src/components/pages/member/memberInfo/MemberInfoUnivList.tsx
  FE/src/components/pages/member/memberInfo/SettingBtn.tsx
  FE/src/constants/memberData.tsx
  FE/src/utils/memberDataFormat.ts
Labels: FE

#111 Feat/#109
  FE/src/apis/charge.ts
  FE/src/apis/funding.ts
  FE/src/components/pages/member/memberInfo/MemberInfoUnivList.tsx
  FE/src/components/pages/pledge/Payment.tsx
  FE/src/components/pages/pledge/Pledge.tsx
  FE/src/hooks/useCharge.tsx
Labels: FE

#114 Feat/#110
  FE/src/apis/charge.ts
  FE/src/apis/funding.ts
  FE/src/app/api/funding/[fundingId]/route.ts
  FE/src/components/pages/charge/ChargingCoin.tsx
  FE/src/components/pages/fundingDetail/Info/FundingDetail.tsx
  FE/src/components/pages/fundingDetail/Info/InfoDonate.tsx
  FE/src/components/pages/fundingDetail/Info/InfoOption.tsx
  FE/src/components/pages/pledge/PaymentBtn.tsx
  FE/src/utils/dataFomat.ts
  FE/src/utils/localData.ts
Labels: FE, :sparkles: Feature

#116 Feat/#115
  FE/src/app/globals.css
  FE/src/components/common/Total.tsx
  FE/src/components/pages/charge/ChargingCoin.tsx
  FE/src/components/pages/charge/RequireDisplay.tsx
Labels: bug, :sparkles: Feature

#119 [BE/REFACTOR] 메인 홈 조회 쿼리 최적화, dto validation 버그 해결
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/dto/FundingReqDtos.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/dto/FundingRespDtos.java
  BE/girin-grim/src/main/java/com/starshop/giringrim/funding/repository/FundingRepositoryCustom.java
  BE/girin-grim/src/test/java/com/starshop/giringrim/funding/repository/FundingRepositoryCustomTest.java
Labels: BE, refactor

#122 Feat/#121
  FE/src/components/pages/layout/modal/UnivTitleUniv.tsx
  FE/src/hooks/useDebounce.tsx
Labels: FE, :sparkles: Feature

#124 feat: 푸터 추가
  FE/public/assets/Footer.svg
  FE/src/app/layout.tsx
  FE/src/components/common/icon.ts
  FE/src/components/common/icons/Footer.tsx
Labels: FE

#126 Feat/#125
  FE/src/components/pages/layout/modal/UnivUlUniv.tsx
  FE/src/constants/RegionData.ts
  FE/src/hooks/useUniv.tsx
  FE/src/store/HeaderState.ts
Labels: bug, FE

#131 Merge pull request #129 from geongyu09/feat/#128
  FE/src/apis/home.ts
  FE/src/components/pages/home/ExtendBtn.tsx
  FE/src/hooks/useUniv.tsx
  FE/src/hooks/useUser.tsx
Labels: FE, :sparkles: Feature

#134 refactor: classname 정리
  FE/package.json
  FE/src/apis/member.ts
  FE/src/app/globals.css
  FE/src/components/common/AgreementCheckbox.tsx
  FE/src/components/common/Grid.tsx
  FE/src/components/common/HomeFeed.tsx
  FE/src/components/common/Options.tsx
  FE/src/components/common/PageTitle.tsx
  FE/src/components/common/StyledBtn.tsx
  FE/src/components/common/Total.tsx
  FE/src/components/common/UnivUl.tsx
  FE/src/components/common/icons/NameTagPng.tsx
  FE/src/components/pages/backed/BackedSection.tsx
  FE/src/components/pages/charge/BalanceDisplay.tsx
  FE/src/components/pages/charge/DevBtn.tsx
  FE/src/components/pages/fundingDetail/Info/InfoOptionDetail.tsx
  FE/src/components/pages/home/HomeBanner.tsx
  FE/src/components/pages/home/HomeHeader.tsx
  FE/src/components/pages/home/Univ.tsx
  FE/src/components/pages/join/JoinBtnInput.tsx
  FE/src/components/pages/join/JoinForm.tsx
  FE/src/components/pages/join/JoinInput.tsx
  FE/src/components/pages/join/modal/UnivUl.tsx
  FE/src/components/pages/layout/HeaderNavSection.tsx
  FE/src/components/pages/layout/UserImage.tsx
  FE/src/components/pages/layout/modal/Category.tsx
  FE/src/components/pages/layout/modal/UnivUlUniv.tsx
  FE/src/components/pages/layout/modal/University.tsx
  FE/src/components/pages/login/LoginInput.tsx
  FE/src/components/pages/member/FundingList/CreateGrid.tsx
  FE/src/components/pages/member/memberInfo/CargeBtn.tsx
  FE/src/components/pages/member/memberInfo/SettingBtn.tsx
  FE/src/components/pages/pledge/Payment.tsx
  FE/src/utils/localData.ts
  FE/tailwind.config.ts
  FE/yarn.lock
Labels: FE

#136 Fix/#135
  FE/src/components/pages/join/modal/UnivUl.tsx
  FE/src/components/pages/layout/modal/UnivTitleUniv.tsx
  FE/src/components/pages/layout/modal/UnivUlUniv.tsx
  FE/src/hooks/useUniv.tsx
Labels: FE

#139 Feat/#138
  FE/src/components/pages/home/ExtendBtn.tsx
  FE/src/components/pages/home/HomeFundingList.tsx
  FE/src/components/pages/join/JoinForm.tsx
  FE/src/store/HomeState.ts
  FE/src/utils/localData.ts
Labels: FE, :sparkles: Feature

#141 Fix/#140
  FE/src/components/common/icons/Setting.tsx
  FE/src/components/pages/charge/ChargeOptionSection.tsx
Labels: bug, FE

#144 Feat/#143
  FE/src/components/common/icons/FilterToggle.tsx
  FE/src/components/common/icons/ToggleArrow.tsx
  FE/src/components/pages/home/ExtendBtn.tsx
  FE/src/components/pages/home/HomeFundingList.tsx
  FE/src/hooks/useFeeds.tsx
  FE/src/store/HomeState.ts
Labels: FE, :sparkles: Feature

#148 Feat/#147
  FE/src/app/favicon.ico
  FE/src/app/funding/[fundingId]/layout.tsx
  FE/src/app/layout.tsx
  FE/src/app/member/layout.tsx
  FE/src/app/page.tsx
Labels: FE

#154 feat: 배너 변경
  FE/public/assets/Banner.svg
  FE/src/components/common/FeedBox.tsx
Labels: FE

#156 Feat/#155
  FE/src/components/pages/charge/ChargeBtn.tsx
  FE/src/components/pages/charge/Payment.tsx
  FE/src/components/pages/fundingDetail/Detail/Description.tsx
  FE/src/components/pages/layout/HeaderNavSection.tsx
Labels: FE

#158 Feat/#157
  FE/src/components/common/icons/User.tsx
  FE/src/components/pages/charge/ChargeBtn.tsx
  FE/src/components/pages/member/FundingList/SupportGrid.tsx
  FE/src/components/pages/member/memberInfo/InfoSectoin.tsx
  FE/src/components/pages/member/memberInfo/MemberHero.tsx
  FE/src/components/pages/member/memberInfo/MemberInfoList.tsx
  FE/src/components/pages/member/memberInfo/MemberInfoUnivList.tsx
  FE/src/components/pages/member/memberInfo/MineInfoSection.tsx
  FE/src/components/pages/member/memberInfo/NotMineInfoSection.tsx
  FE/src/utils/cssFormat.ts
Labels: FE

#162 Fix/#161
  FE/src/components/pages/charge/ChargingCoin.tsx
  FE/src/components/pages/fundingDetail/Info/GaugeBar.tsx
  FE/src/components/pages/pledge/PaymentBtn.tsx
  FE/src/utils/dataFomat.ts
Labels: bug, FE
